# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            John Wang
tagline:          'Full-Stack Software Engineer'
description:      'Full-Stack Software Engineer'
url:              http://johnw424.github.io/blog/
baseurl:          /

author:
  name:           'John Wang'
  url:            http://johnw424.github.io/blog/

paginate:         5
